### ISSUE TITLE
Adscend Offer Wall in mobiles issue

### ISSUE THREAD

**Issue by mcdeimon** [VidYen/VidYen-WordPress-Plugins#97]
Adscend Offer Wall does not work on many phones.

**Comment by VidYen** [comment]
No it does not. On my phone it actually tells me it won't work on Safari via pop up saying Safari browser not support by Adscend.

I have an Android tablet laying around and I can try that.

Do you have an Apple, Android, or something else? Also what browser are you using on the phone?

I have a feeling Adscend is using stuff normal browsers have that Apple is frowning on.

**Comment by mcdeimon** [comment]
On my android mobile using Chrome works perfectly. Some users have told me that it does not work for them on their phones. I'm going to ask them what they're using.

**Comment by mcdeimon** [comment]
An user has told me that he has used this mobile:

Android 7.1, Chrome, motog5splus.

**Comment by VidYen** [comment]
Thank you for info! I tried Chrome on my phone does not work it seems. I will try my Android tablet later today. I think I will reach out to Adscend though as I have a feeling they are doing something different now as it used to work on my Google Chrome on my iPhone.

**Comment by VidYen** [comment]
This issue is way out of date.
